[project]
name = "mcp-faq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.5",
    "minsearch>=0.0.7",
    "pydantic-ai[mcp]>=1.1.0",
    "requests>=2.32.5",
    "toyaikit>=0.0.4",
]
